spring:
  datasource:
    url: jdbc:h2:mem:testdb  # Use an in-memory H2 database
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true  # Enable H2 console for development purposes
      path: /h2-console  # Default path for the H2 console