server:
  port: 8181

spring:
  profiles:
    active:
    group:
      local :
        - db
        - jpa
        - logging
        - naver
        - kakao
        - aladin

      main :
        - db
        - jpa
        - logging
        - naver
        - kakao
        - aladin